# Generated by Django 6.0.6 on 2026-06-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corepython', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-date'], 'permissions': [('can_view_reports', 'Может просматривать отчёты')], 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
    ]
